# Generated by Django 4.1.3 on 2022-12-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=30, null=False)),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(blank=True, upload_to='news_post')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
