# Generated by Django 4.1.3 on 2022-12-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newspost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='media',
            new_name='image',
        ),
        migrations.AddField(
            model_name='newspost',
            name='link_to_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
