# Generated by Django 4.1.3 on 2022-12-09 12:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newspost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='link_to_video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
