# Generated by Django 4.1.3 on 2022-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newspost_link_to_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
