# Generated by Django 4.1.3 on 2022-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newspost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
