# Generated by Django 4.1.3 on 2022-12-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidecategory',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
