# Generated by Django 4.1.3 on 2022-12-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_alter_guidecategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidecategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
