# Generated by Django 4.1.3 on 2022-12-11 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_game_updated_on'),
        ('guides', '0003_guidecategory_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('publication_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='guides.guidecategory')),
                ('to_game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='games.game')),
            ],
        ),
    ]
