# Generated by Django 4.1.3 on 2022-12-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_guidepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepost',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
