# Generated by Django 4.1.3 on 2022-12-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_updated_on'),
        ('guides', '0005_guidepost_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidepost',
            name='to_game',
        ),
        migrations.AddField(
            model_name='guidecategory',
            name='to_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='games.game'),
            preserve_default=False,
        ),
    ]
