# Generated by Django 4.1.3 on 2022-12-13 11:31

import django.core.validators
from django.db import migrations, models
import next_level.validators


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_remove_guidepost_to_game_guidecategory_to_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidecategory',
            name='title',
            field=models.CharField(max_length=50, validators=[next_level.validators.validate_all_characters_is_alphanumeric, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='guidepost',
            name='title',
            field=models.CharField(max_length=50, validators=[next_level.validators.validate_all_characters_is_alphanumeric, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
