# Generated by Django 4.1.3 on 2022-12-14 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0007_alter_guidecategory_title_alter_guidepost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidecategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
