# Generated by Django 4.1.3 on 2022-12-14 16:49

import django.core.validators
from django.db import migrations, models
import next_level.validators


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0009_guidepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidecategory',
            name='title',
            field=models.CharField(max_length=50, validators=[next_level.validators.validate_post_title_contains_only_allowed_characters, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='guidepost',
            name='title',
            field=models.CharField(max_length=50, validators=[next_level.validators.validate_post_title_contains_only_allowed_characters, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
