version: '3.4'

services:
  web:
    build: .
    command: gunicorn next_level.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./media:/home/app/web/media
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: davq4a
      POSTGRES_USER: davq4a
      POSTGRES_DB: next_level
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack
  celery:
    restart: always
    build:
      context: .
    command: celery -A web worker -l info
    volumes:
      - ./web:/web
    environment:
      - DB_HOST=postgres
      - DB_NAME=next_level
      - DB_USER=davq4a
      - DB_PASS=davq4a
    depends_on:
      - postgres
      - redis
      - web
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 81:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./media:/home/app/web/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
