# Generated by Django 4.1.3 on 2022-12-09 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newspost_description_alter_newspost_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_alter_comment_options_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_news_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='news.newspost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_news_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='news.newspost'),
        ),
    ]
