# Generated by Django 4.1.3 on 2022-12-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='game',
        ),
    ]
