# Generated by Django 4.1.3 on 2022-12-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newspost_updated_on'),
        ('common', '0006_comment_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='to_guide_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='guide_post', to='news.newspost'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_news_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='news.newspost'),
        ),
    ]
