# Generated by Django 4.1.3 on 2022-12-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_remove_guidepost_to_game_guidecategory_to_game'),
        ('common', '0008_alter_like_to_guide_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='to_guide_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='guides_like_set', to='guides.guidepost'),
        ),
    ]
