# Generated by Django 4.1.3 on 2022-12-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
